import type { UiStrings } from '../types.js';

const plural = (count: number, one: string, many: string): string =>
  `${count} ${count === 1 ? one : many}`;

export const en: UiStrings = {
  title: 'WordBlocks',
  intro: [
    'A block lists its categories above it — only their words count. ' +
      'Connect a word by swiping across neighbouring tiles, no diagonals.',
    'Several words fit, but you take one: it crumbles the block along with the rest. ' +
      'The goal counts letters, so a short word is letters lost.',
    'A word outside the categories goes to your collection and pays coins, and coins buy hints.',
  ],
  build: (stamp) => `build ${stamp}`,
  locked: '🔒',
  noResult: '—',
  toMap: 'Levels',
  toMapTitle: 'back to the level map',
  fullscreen: 'Full screen',
  fullscreenExit: 'Exit',
  fullscreenTitle: 'play full screen',
  soundOff: 'turn the sound off',
  soundOn: 'turn the sound on',
  hint: 'Hint',
  hintTitle: 'light up the first letter of the long word',
  tutorHint: 'Connect letters into a word',
  blockWord: 'Block',
  blockOf: (index, total) => `${index} of ${total}`,
  levelName: (index) => `Level ${index}`,
  levelNameShort: (index) => `Lvl ${index}`,
  won: 'Brilliant!',
  lost: 'Not enough letters',
  perfect: 'Flawless: the longest word taken in every block.',
  wellDone: 'Level cleared.',
  reward: (coins) => `+${coins}`,
  hintCost: (coins) => `${coins}`,
  notEnoughCoins: 'Not enough coins',
  collected: (letters, goal) => `${plural(letters, 'letter', 'letters')} of ${goal} collected.`,
  lostEarly: ' The remaining blocks could not cover the goal, so the level ended early.',
  next: 'Next level',
  retry: 'Try again',
  lastChance: 'Last chance',
  plusBlock: '+1 block',
  bonusTitle: 'Extra words',
  bonusButtonTitle: 'words outside the theme you found along the way',
  bonusHere: 'On this level:',
  bonusEmpty: 'Nothing yet. A word outside the level categories keeps the block standing and lands here instead.',
  bonusTotal: (count) => `Found in total: ${count}`,
  bonusProgress: (count, goal) => `${count} / ${goal}`,
  bonusPaid: (coins) => `+${coins} for the collection`,
  bonusFound: 'collected',
  bonusAgain: 'already found',
  bonusClose: 'Got it',
};
